include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/_base.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/packaging-docker/dockerfile-linting.yml'
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/scanning/container-scanning.yml'

stages:
  - pre-package
  - package
  - post-package

.docker-login-gitlab: &docker-login-gitlab |
  env | grep "^CI_JOB_TOKEN=" | cut -d '=' -f 2- | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}

.docker-login-dockerhub: &docker-login-dockerhub |
  env | grep "^DOCKER_HUB_PASS=" | cut -d '=' -f 2- | docker login -u ${DOCKER_HUB_USER} --password-stdin

.create-multiarch-builder: &create-multiarch-builder |
  docker buildx create --driver docker-container --name multiarch-builder --use > /dev/null

.docker-compose-build: &docker-compose-build >
  COMPOSE_FILE=${COMPOSE_PROJECT_DIRECTORY}/${COMPOSE_FILE_NAME}
  IMAGE_NAME=${PACKAGED_IMAGE_NAME}
  IMAGE_TAG=${PACKAGED_IMAGE_TAG}
  docker compose
  --env-file ${COMPOSE_PROJECT_DIRECTORY}/${COMPOSE_ENV_FILE_NAME}
  build
  -q
  --pull
  --push
  ${DOCKER_BUILD_ARGS};

.docker-build:
  extends: .dind-env
  stage: package
  image: ${PACKAGING_IMAGE_NAME}:${PACKAGING_IMAGE_TAG}
  variables:
    PACKAGING_IMAGE_NAME: docker
    PACKAGING_IMAGE_TAG: latest
    PACKAGED_IMAGE_NAME: ${CI_REGISTRY_IMAGE}
    IMAGETOOLS_CREATE_PROGRESS: none
    COMPOSE_FILE_NAME: compose.yaml
    COMPOSE_ENV_FILE_NAME: .env
    COMPOSE_PROJECT_DIRECTORY: '.'
    BUILDX_GIT_INFO: 'false'

.docker-branch:
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_COMMIT_TAG ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH

.docker-tag:
  rules:
    - if: $CI_COMMIT_TAG &&
          $CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+.*/i

docker-build-branch:
  extends:
    - .docker-build
    - .docker-branch
  variables:
    PACKAGED_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}
    LATEST_TAG_VALUE: ${CI_COMMIT_REF_SLUG}
    VERSION: ${CI_COMMIT_SHORT_SHA}
  script:
    - *docker-login-gitlab
    - *create-multiarch-builder
    - *docker-compose-build
    - >
      docker buildx imagetools create
      --tag ${PACKAGED_IMAGE_NAME}:${LATEST_TAG_VALUE}
      --progress ${IMAGETOOLS_CREATE_PROGRESS}
      ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG}

docker-build-tag:
  extends:
    - .docker-build
    - .docker-tag
  variables:
    PACKAGED_IMAGE_TAG: ${CI_COMMIT_TAG}
    LATEST_TAG_VALUE: latest
    VERSION: ${CI_COMMIT_TAG}
  script:
    - *docker-login-gitlab
    - *create-multiarch-builder
    - *docker-compose-build
    - *docker-login-dockerhub
    - >
      dockerHubImagePath="$(echo ${CI_PROJECT_PATH} | cut -d '/' -f 2- | sed 's/\//-/g')";
      dockerHubImage="${DOCKER_HUB_ROOT}/${dockerHubImagePath}"
    - >
      docker buildx imagetools create
      --tag ${PACKAGED_IMAGE_NAME}:${LATEST_TAG_VALUE}
      --tag ${dockerHubImage}:${CI_COMMIT_TAG}
      --tag ${dockerHubImage}:${LATEST_TAG_VALUE}
      --progress ${IMAGETOOLS_CREATE_PROGRESS}
      ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG}

# Temporary fix until resolved at template level
container_scanning:
  variables:
    CI_APPLICATION_REPOSITORY: ${CI_REGISTRY_IMAGE}
    CI_APPLICATION_TAG: ${CI_COMMIT_SHORT_SHA}
