include:
  - project: 'pedroetb-projects/gitlab-ci-templates'
    ref: master
    file: '/_packaging.yml'

stages:
  - pre-package
  - package
  - post-package

.docker-login-gitlab: &docker-login-gitlab |
  docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

.docker-login-dockerhub: &docker-login-dockerhub |
  docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASS}

.docker-operations:
  extends: .docker-env
  variables:
    PACKAGED_IMAGE_NAME: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}
    PACKAGED_IMAGE_TAG: ${CI_COMMIT_SHA}
    LATEST_TAG_VALUE: latest

docker-build:
  extends: .docker-operations
  stage: package
  image: ${PACKAGING_IMAGE_NAME}:${PACKAGING_IMAGE_TAG}
  variables:
    PACKAGING_IMAGE_NAME: docker
    PACKAGING_IMAGE_TAG: latest
    COMPOSE_FILE_NAME: compose.yaml
    COMPOSE_ENV_FILE_NAME: .env
    COMPOSE_PROJECT_DIRECTORY: '.'
  script:
    - *docker-login-gitlab
    - >
      COMPOSE_FILE=${COMPOSE_PROJECT_DIRECTORY}/${COMPOSE_FILE_NAME}
      IMAGE_NAME=${PACKAGED_IMAGE_NAME}
      IMAGE_TAG=${PACKAGED_IMAGE_TAG}
      docker compose
      --env-file ${COMPOSE_PROJECT_DIRECTORY}/${COMPOSE_ENV_FILE_NAME}
      build
      --pull
      ${DOCKER_BUILD_ARGS};
    - docker tag ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG} ${PACKAGED_IMAGE_NAME}:${LATEST_TAG_VALUE}
    - docker push ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG}
    - docker push ${PACKAGED_IMAGE_NAME}:${LATEST_TAG_VALUE}
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH ||
          $CI_COMMIT_TAG

.docker-tag:
  extends: .docker-operations
  stage: post-package
  dependencies: []
  rules:
    - if: $CI_MERGE_REQUEST_ID ||
          $CI_PIPELINE_SOURCE == "schedule" ||
          $CI_COMMIT_BRANCH
      when: never
    - if: $CI_COMMIT_TAG

docker-tag-gitlab:
  extends: .docker-tag
  script:
    - *docker-login-gitlab
    - docker pull ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG}
    - docker tag ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG} ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker tag ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG} ${CI_REGISTRY_IMAGE}:${LATEST_TAG_VALUE}
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${CI_REGISTRY_IMAGE}:${LATEST_TAG_VALUE}

docker-tag-dockerhub:
  extends: .docker-tag
  script:
    - *docker-login-gitlab
    - *docker-login-dockerhub
    - docker pull ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG}
    - dockerHubImagePath="$(echo ${CI_PROJECT_PATH} | cut -d '/' -f 2- | sed 's/\//-/g')"
    - dockerHubImage="${DOCKER_HUB_ROOT}/${dockerHubImagePath}"
    - docker tag ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG} ${dockerHubImage}:${CI_COMMIT_TAG}
    - docker tag ${PACKAGED_IMAGE_NAME}:${PACKAGED_IMAGE_TAG} ${dockerHubImage}:${LATEST_TAG_VALUE}
    - docker push ${dockerHubImage}:${CI_COMMIT_TAG}
    - docker push ${dockerHubImage}:${LATEST_TAG_VALUE}
