services:
  docker-build:
    image: ${IMAGE_NAME:-pedroetb/docker-build}:${IMAGE_TAG:-latest}
    build:
      context: ${BUILD_CONTEXT:-.}
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        DOCKER_VERSION:
        OPENSSH_VERSION:
        VERSION:
      platforms:
        - linux/amd64
        - linux/arm64/v8
        - linux/arm/v7
        - linux/arm/v6
